### ISSUE TITLE
[ADD WEBSITE]: www.xcodebuild.com

### ISSUE THREAD

**Issue by xcodebuild** [FeedsPub/badge#4]
I am using Feeds Pub badge on my website

- Website URL: https://www.xcodebuild.com/
- Feed URL: https://www.xcodebuild.com/atom.xml

**Comment by timqian** [comment]
@xcodebuild 感谢使用! 你的 feed 用 `rss-parser` parse 的时候遇到一点问题
```
failed getting feed Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```
, 不过我找到了相关的 issue, 尽快把它修好加上

https://github.com/rbren/rss-parser/issues/137

**Comment by timqian** [comment]
Fixed

<img width="608" alt="Screen Shot 2020-04-29 at 11 50 45 PM" src="https://user-images.githubusercontent.com/5512552/80617371-98a4d480-8a74-11ea-9ce4-8632ad53da67.png">

欢迎在 feeds.pub claim 这个博客: https://feeds.pub/feed/https%3A%2F%2Fwww.xcodebuild.com%2Fatom.xml

**Comment by timqian** [comment]
added https://xcodebuild.com to https://badge.feeds.pub
